project_id = "gytjgmeoepglbrjrbfie"

[functions.export-login-history]
verify_jwt = true

[functions.image-scrape]
verify_jwt = true

[functions.import-weekend-matrix-commit]
verify_jwt = true

[functions.media-optimizer]
verify_jwt = false
