// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gytjgmeoepglbrjrbfie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dGpnbWVvZXBnbGJyanJiZmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODE0MDgsImV4cCI6MjA2OTY1NzQwOH0.NZd_8dw_B0LNGmko5odGGhI6r1Qc5Xx_X0zW9CidRe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});